// Type shim for the bundle generated by `wdk-worklet-bundler`.
// The file is CommonJS (`module.exports = "..."`), so when required it
// resolves to the worklet source as a string.
declare module '*/wdk-worklet.bundle.js' {
  const bundle: string;
  export = bundle;
}
