/**
 * WalletProviders
 *
 * Wraps the entire app with the WDK provider (worklet + secure storage + react
 * query) and the UI Kit theme provider. The worklet bundle is imported from
 * `./.wdk/index.ts` which is generated by `npx wdk-worklet-bundler generate`.
 */
import { WdkAppProvider } from '@tetherto/wdk-react-native-core';
import { ThemeProvider as WdkThemeProvider } from '@tetherto/wdk-uikit-react-native';

import { wdkConfigs } from '@/config/wdk';
import { usePreferences } from '@/store/preferences';

// Bundle generated by `npx wdk-worklet-bundler generate`. The bundler emits the
// file as a CommonJS module whose default export is the worklet source string,
// so we `require` it directly per the @tetherto/wdk-worklet-bundler README.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const workletBundle: string = require('../../../.wdk-bundle/wdk-worklet.bundle.js');

export const WalletProviders = ({ children }: { children: React.ReactNode }) => {
  const themePref = usePreferences((s) => s.theme);
  const defaultMode = themePref === 'system' ? 'auto' : themePref;

  return (
    <WdkAppProvider
      bundle={{ bundle: workletBundle }}
      wdkConfigs={wdkConfigs}
      clearSensitiveDataOnBackground>
      <WdkThemeProvider defaultMode={defaultMode}>{children}</WdkThemeProvider>
    </WdkAppProvider>
  );
};
